#!/usr/bin/python3
# COMP3311 20T3 Ass3 ... print name, year, ratings of top N movies
# Zixuan Guo z5173593

import sys
import psycopg2
#from helpers import whatever, functions, you, need

# define any local helper functions here

# set up some globals

usage = "Usage: best [N]"
db = None

# process command-line args

argc = len(sys.argv)
if argc > 2:
  print("Usage: best [N]")
  exit(1)

if argc == 1:
  num = 10
elif argc == 2:
  try:
    num = int(sys.argv[1])
  except ValueError:  
    print("Usage: best [N]")
    exit(1)
  if num < 1:
    print("Usage: best [N]")
    exit(1)

# create query
query = """
select rating, title, start_year from movies
order by rating desc, title;
"""

# manipulate database
try:
  db = psycopg2.connect("dbname=imdb")
  cur = db.cursor()
  cur.execute(query)
  movie = cur.fetchmany(num)

  for rating in movie:
    print(str(rating[0]), str(rating[1]), '(' + str(rating[2]) + ')')

except psycopg2.Error as err:
  print("DB error: ", err)
finally:
  if db:
    db.close()

